import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, Clock3, Heart, Loader2, Play, Search, Tv } from 'lucide-react';
import type { Channel } from '@/types';
import { loadSeriesCatalog, loadSeriesDetails, type SeriesCategory, type SeriesEpisode, type SeriesShow } from '@/lib/provider';
import { storage } from '@/lib/storage';

interface SeriesViewProps { channels: Channel[]; groups: string[]; favorites: Set<string>; onSelectChannel: (ch: Channel) => void; onToggleFavorite: (id: string) => void; }
const LATEST = 'recent';
const text = (value: unknown) => typeof value === 'string' || typeof value === 'number' ? String(value) : '';

export function SeriesView({ favorites, onSelectChannel, onToggleFavorite }: SeriesViewProps) {
  const [categories, setCategories] = useState<SeriesCategory[]>([]);
  const [shows, setShows] = useState<SeriesShow[]>([]);
  const [activeCategory, setActiveCategory] = useState(LATEST);
  const [selected, setSelected] = useState<SeriesShow | null>(null);
  const [episodes, setEpisodes] = useState<SeriesEpisode[]>([]);
  const [season, setSeason] = useState(1);
  const [query, setQuery] = useState('');
  const [loading, setLoading] = useState(true);
  const [detailLoading, setDetailLoading] = useState(false);
  const [seriesInfo, setSeriesInfo] = useState<Record<string, unknown>>({});
  const [progress, setProgress] = useState(() => storage.getWatchProgress());

  useEffect(() => { let active = true; void loadSeriesCatalog().then((catalog) => { if (!active || !catalog) return; setCategories(catalog.categories); setShows(catalog.shows); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const categoryShows = useMemo(() => { const base = activeCategory === LATEST ? [...shows].sort((a, b) => Number(b.added || 0) - Number(a.added || 0)) : shows.filter((show) => show.categoryId === activeCategory); const value = query.trim().toLocaleLowerCase('pt-BR'); return (value ? base.filter((show) => show.name.toLocaleLowerCase('pt-BR').includes(value)) : base).slice(0, activeCategory === LATEST ? 80 : 500); }, [activeCategory, query, shows]);
  const selectShow = async (show: SeriesShow) => { setSelected(show); setEpisodes([]); setSeriesInfo({}); setDetailLoading(true); setProgress(storage.getWatchProgress()); window.scrollTo({ top: 0, behavior: 'smooth' }); try { const details = await loadSeriesDetails(show.seriesId); if (details) { setEpisodes(details.episodes); setSeriesInfo(details.info); setSeason(details.episodes[0]?.season || 1); } } finally { setDetailLoading(false); } };
  const seasons = useMemo(() => [...new Set(episodes.map((item) => item.season))].sort((a, b) => a - b), [episodes]);
  const seasonEpisodes = episodes.filter((item) => item.season === season).sort((a, b) => a.episode - b.episode);
  const continueEpisode = episodes.find((item) => progress[item.id] && progress[item.id].current < progress[item.id].duration - 30) || episodes[0];

  if (!selected) return <div className="-mx-5 -mt-6 min-h-screen bg-[#091018] sm:-mx-8 lg:-mx-10 lg:-mt-8"><div className="grid min-h-screen lg:grid-cols-[17rem_1fr]">
    <aside className="border-b border-white/[0.035] bg-[#0b141b] p-4 lg:border-b-0 lg:border-r lg:p-5"><div className="relative mb-3"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-white/30" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Procurar" className="w-full rounded-xl bg-white/[0.055] py-3 pl-9 pr-3 text-sm text-white outline-none placeholder:text-white/30" /></div><div className="flex gap-2 overflow-x-auto scrollbar-none lg:max-h-[calc(100vh-7rem)] lg:flex-col lg:overflow-y-auto"><button onClick={() => setActiveCategory(LATEST)} className={`shrink-0 rounded-xl px-4 py-3 text-left text-sm transition ${activeCategory === LATEST ? 'bg-emerald-400 text-slate-950' : 'bg-white/[0.035] text-white/55 hover:bg-white/[0.07]'}`}>Últimos adicionados</button>{categories.map((category) => <button key={category.id} onClick={() => setActiveCategory(category.id)} className={`shrink-0 rounded-xl px-4 py-3 text-left text-sm transition ${activeCategory === category.id ? 'bg-emerald-400 text-slate-950' : 'bg-white/[0.035] text-white/55 hover:bg-white/[0.07]'}`}>{category.name}</button>)}</div></aside>
    <main className="min-w-0 p-5 sm:p-7 lg:p-8"><div className="mb-6 flex items-end justify-between"><div><p className="text-[10px] uppercase tracking-[.18em] text-emerald-400">Séries</p><h1 className="mt-1 text-2xl font-semibold">{activeCategory === LATEST ? 'Últimos adicionados' : categories.find((item) => item.id === activeCategory)?.name}</h1></div><span className="text-xs text-white/30">{categoryShows.length} títulos</span></div>{loading ? <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 xl:grid-cols-4">{Array.from({ length: 8 }).map((_, index) => <div key={index} className="aspect-[2/3] animate-pulse rounded-2xl bg-white/[0.045]" />)}</div> : <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5">{categoryShows.map((show) => <button key={show.id} onClick={() => void selectShow(show)} className="group text-left"><div className="aspect-[2/3] overflow-hidden rounded-2xl bg-white/[0.04]">{show.logo ? <img src={show.logo} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <span className="flex h-full items-center justify-center"><Tv className="h-9 w-9 text-white/15" /></span>}</div><p className="mt-2 truncate text-sm font-medium text-white/75">{show.name}</p>{Number(show.rating) > 0 && <p className="mt-0.5 text-[10px] text-amber-300">★ {show.rating}</p>}</button>)}</div>}</main>
  </div></div>;

  const infoBackdrop = text(seriesInfo.backdrop_path || seriesInfo.backdrop) || selected.backdrop || selected.logo;
  const plot = text(seriesInfo.plot || seriesInfo.description) || selected.plot;
  const genre = text(seriesInfo.genre) || selected.genre;
  const release = text(seriesInfo.releaseDate || seriesInfo.release_date) || selected.releaseDate;
  return <div className="-mx-5 sm:-mx-8 lg:-mx-10 lg:-mt-8"><section className="relative min-h-[72vh] overflow-hidden bg-[#0a1117]">{infoBackdrop && <img src={infoBackdrop} alt="" className={`absolute inset-0 h-full w-full ${selected.backdrop ? 'object-cover' : 'scale-110 object-cover opacity-48 blur-2xl'}`} />}<div className="absolute inset-0 bg-[linear-gradient(90deg,#091018_0%,rgba(9,16,24,.82)_48%,rgba(9,16,24,.14)_100%),linear-gradient(0deg,#091018_0%,transparent_65%)]" /><button onClick={() => setSelected(null)} className="absolute left-5 top-6 z-20 flex items-center gap-2 rounded-xl bg-black/35 px-3 py-2 text-xs text-white/70 backdrop-blur-lg sm:left-8 lg:left-12"><ArrowLeft className="h-4 w-4" />Voltar para capas</button><div className="relative z-10 flex min-h-[72vh] max-w-2xl flex-col justify-end px-5 pb-14 pt-24 sm:px-8 lg:px-12"><span className="mb-3 text-[10px] font-semibold uppercase tracking-[.2em] text-emerald-400">{categories.find((item) => item.id === selected.categoryId)?.name || 'Série'}</span><h1 className="text-4xl font-semibold leading-none tracking-tight lg:text-6xl">{selected.name}</h1><div className="mt-4 flex gap-3 text-xs text-white/48">{release && <span>{release.match(/\d{4}/)?.[0]}</span>}{genre && <span>{genre}</span>}{selected.rating && Number(selected.rating) > 0 && <span className="text-amber-300">★ {selected.rating}</span>}</div>{plot && <p className="mt-4 line-clamp-3 text-sm leading-6 text-white/55">{plot}</p>}<div className="mt-6 flex gap-3">{continueEpisode && <button onClick={() => onSelectChannel(continueEpisode)} className="flex items-center gap-2 rounded-xl bg-emerald-400 px-5 py-3 text-sm font-semibold text-slate-950"><Play className="h-4 w-4 fill-current" />{progress[continueEpisode.id] ? 'Continuar' : 'Reproduzir'}</button>}<button onClick={() => onToggleFavorite(selected.id)} className="flex items-center gap-2 rounded-xl bg-white/10 px-5 py-3 text-sm backdrop-blur"><Heart className={`h-4 w-4 ${favorites.has(selected.id) ? 'fill-emerald-400 text-emerald-400' : ''}`} />Favoritos</button></div>{continueEpisode && progress[continueEpisode.id] && <p className="mt-3 flex items-center gap-1 text-xs text-white/38"><Clock3 className="h-3.5 w-3.5" />Temporada {continueEpisode.season} • Episódio {continueEpisode.episode}</p>}</div></section>
    <section className="px-5 pb-16 pt-6 sm:px-8 lg:px-12">{detailLoading ? <div className="flex min-h-48 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-emerald-400" /></div> : <><h2 className="mb-3 text-sm font-semibold text-white/75">Temporadas</h2><div className="mb-8 flex gap-3 overflow-x-auto scrollbar-none">{seasons.map((value) => <button key={value} onClick={() => setSeason(value)} className={`min-w-44 shrink-0 rounded-xl px-5 py-4 text-sm font-medium ${season === value ? 'bg-emerald-400 text-slate-950' : 'bg-white/[0.06] text-white/55'}`}>Temporada {value}</button>)}</div><h2 className="mb-4 text-lg font-semibold">Episódios</h2><div className="flex gap-4 overflow-x-auto pb-4 scrollbar-none">{seasonEpisodes.map((item) => { const watched = progress[item.id]; const percent = watched ? Math.min(100, Math.round((watched.current / watched.duration) * 100)) : 0; return <button key={item.id} onClick={() => onSelectChannel(item)} className="group w-[min(78vw,22rem)] shrink-0 text-left"><div className="relative aspect-video overflow-hidden rounded-2xl bg-white/[0.04]">{item.logo ? <img src={item.logo} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <span className="flex h-full items-center justify-center"><Tv className="h-8 w-8 text-white/15" /></span>}<div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-transparent" />{percent > 0 && <span className="absolute inset-x-0 bottom-0 h-1.5 bg-white/15"><span className="block h-full bg-emerald-400" style={{ width: `${percent}%` }} /></span>}<span className="absolute bottom-4 left-4 text-sm font-semibold">Episódio {item.episode}</span></div><p className="mt-2 truncate text-xs text-white/45">{item.name}{percent > 0 ? ` • ${percent}% assistido` : ''}</p></button>; })}</div></>}</section>
  </div>;
}
