import { useCallback, useMemo, useState } from 'react';
import { ArrowLeft, Clapperboard, Grid3X3, Heart, Loader2, Play, Tv } from 'lucide-react';
import type { Channel } from '@/types';
import { getChannels } from '@/lib/playlistStore';
import { storage } from '@/lib/storage';

interface SeriesViewProps { channels: Channel[]; groups: string[]; favorites: Set<string>; onSelectChannel: (ch: Channel) => void; onToggleFavorite: (id: string) => void; }
interface Episode { channel: Channel; season: number; episode: number; title: string; }
interface Show { key: string; name: string; cover?: string; episodes: Episode[]; }
type Screen = 'categories' | 'catalog' | 'detail';

function episodeData(channel: Channel, fallback: number): Episode & { showName: string } {
  const name = channel.name.trim();
  const patterns = [/(.*?)[\s._-]+S(\d{1,2})\s*E(\d{1,3})(?:[\s._-]+(.*))?$/i, /(.*?)[\s._-]+T(\d{1,2})\s*E(\d{1,3})(?:[\s._-]+(.*))?$/i, /(.*?)[\s._-]+(\d{1,2})x(\d{1,3})(?:[\s._-]+(.*))?$/i, /(.*?)\s+Temporada\s*(\d+).*?Epis[oó]dio\s*(\d+)(?:\s*[-–]\s*(.*))?$/i];
  for (const pattern of patterns) { const match = name.match(pattern); if (match) return { channel, showName: match[1].replace(/[._]+/g, ' ').trim(), season: Number(match[2]), episode: Number(match[3]), title: match[4]?.replace(/[._]+/g, ' ').trim() || `Episódio ${Number(match[3])}` }; }
  return { channel, showName: name.replace(/\s*[-–]\s*(?:ep(?:is[oó]dio)?\s*)?\d+\s*$/i, '').trim(), season: 1, episode: fallback + 1, title: `Episódio ${fallback + 1}` };
}

function makeShows(items: Channel[]): Show[] {
  const map = new Map<string, Show>();
  items.forEach((channel, index) => { const parsed = episodeData(channel, index); const key = parsed.showName.toLocaleLowerCase('pt-BR'); const show = map.get(key) || { key, name: parsed.showName, cover: channel.logo, episodes: [] }; show.cover ||= channel.logo; show.episodes.push(parsed); map.set(key, show); });
  return [...map.values()].map((show) => ({ ...show, episodes: show.episodes.sort((a, b) => a.season - b.season || a.episode - b.episode) }));
}

export function SeriesView({ groups, favorites, onSelectChannel, onToggleFavorite }: SeriesViewProps) {
  const [screen, setScreen] = useState<Screen>('categories');
  const [activeGroup, setActiveGroup] = useState<string | null>(null);
  const [shows, setShows] = useState<Show[]>([]);
  const [selected, setSelected] = useState<Show | null>(null);
  const [season, setSeason] = useState(1);
  const [loading, setLoading] = useState(false);
  const [progress, setProgress] = useState(() => storage.getWatchProgress());

  const loadGroup = useCallback(async (group: string) => {
    setActiveGroup(group); setScreen('catalog'); setSelected(null); setLoading(true); setShows([]);
    try { setShows(makeShows(await getChannels('series', 1200, 0, group))); } catch { setShows([]); } finally { setLoading(false); }
  }, []);
  const selectShow = useCallback((show: Show) => { setSelected(show); setSeason(show.episodes[0]?.season || 1); setProgress(storage.getWatchProgress()); setScreen('detail'); window.scrollTo({ top: 0, behavior: 'smooth' }); }, []);
  const seasons = useMemo(() => selected ? [...new Set(selected.episodes.map((item) => item.season))] : [], [selected]);
  const episodes = selected?.episodes.filter((item) => item.season === season) || [];
  const firstEpisode = episodes[0] || selected?.episodes[0];

  if (screen === 'categories') return <div className="mt-6 pb-16"><div className="mb-8 flex items-center gap-3"><span className="rounded-xl bg-emerald-400/12 p-2.5 text-emerald-300"><Clapperboard className="h-5 w-5" /></span><div><h1 className="text-2xl font-semibold">Séries</h1><p className="text-xs text-white/40">Escolha uma categoria para continuar</p></div></div>{groups.length ? <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{groups.map((group) => <button key={group} onClick={() => void loadGroup(group)} className="group flex min-h-20 items-center gap-4 rounded-2xl bg-white/[0.035] p-4 text-left transition hover:bg-white/[0.075]"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-400/10 text-emerald-300 transition group-hover:bg-emerald-400 group-hover:text-slate-950"><Grid3X3 className="h-5 w-5" /></span><span className="line-clamp-2 text-sm font-medium text-white/70 group-hover:text-white">{group}</span></button>)}</div> : <div className="py-20 text-center text-sm text-white/40">Nenhuma categoria encontrada.</div>}</div>;

  if (screen === 'catalog') return <div className="mt-6 pb-16"><div className="mb-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><button onClick={() => setScreen('categories')} className="rounded-xl bg-white/[0.055] p-2.5 text-white/55 transition hover:bg-white/10 hover:text-white"><ArrowLeft className="h-5 w-5" /></button><div><p className="text-[10px] uppercase tracking-[.18em] text-emerald-400">Séries</p><h1 className="text-2xl font-semibold">{activeGroup}</h1></div></div><select value={activeGroup || ''} onChange={(event) => void loadGroup(event.target.value)} className="min-w-64 rounded-xl bg-[#121c24] px-4 py-3 text-sm text-white/75 outline-none ring-1 ring-white/[0.06] focus:ring-emerald-400/35">{groups.map((group) => <option key={group} value={group}>{group}</option>)}</select></div>{loading ? <div className="flex min-h-72 items-center justify-center"><Loader2 className="h-8 w-8 animate-spin text-emerald-400" /></div> : shows.length ? <div className="grid grid-cols-2 gap-3 sm:grid-cols-3 md:grid-cols-4 xl:grid-cols-6">{shows.map((show) => <button key={show.key} onClick={() => selectShow(show)} className="group text-left"><div className="aspect-[2/3] overflow-hidden rounded-2xl bg-white/[0.04] shadow-xl shadow-black/10">{show.cover ? <img src={show.cover} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <span className="flex h-full items-center justify-center"><Tv className="h-8 w-8 text-white/15" /></span>}</div><p className="mt-2 truncate text-sm font-medium text-white/70 group-hover:text-white">{show.name}</p><p className="mt-0.5 text-[10px] text-white/30">{show.episodes.length} episódios</p></button>)}</div> : <div className="py-20 text-center text-sm text-white/40">Nenhuma série encontrada nesta categoria.</div>}</div>;

  return <div className="-mx-5 sm:-mx-8 lg:-mx-10 lg:-mt-8">{selected && <section className="relative min-h-[68vh] overflow-hidden bg-[#0a1117]">{selected.cover && <img src={selected.cover} alt="" className="absolute inset-0 h-full w-full scale-110 object-cover opacity-48 blur-2xl" />}<div className="absolute inset-0 bg-[linear-gradient(90deg,#091018_0%,rgba(9,16,24,.82)_48%,rgba(9,16,24,.2)_100%),linear-gradient(0deg,#091018_0%,transparent_60%)]" /><button onClick={() => setScreen('catalog')} className="absolute left-5 top-6 z-20 flex items-center gap-2 rounded-xl bg-black/35 px-3 py-2 text-xs text-white/70 backdrop-blur-lg hover:text-white sm:left-8 lg:left-12"><ArrowLeft className="h-4 w-4" />Voltar para séries</button><div className="relative z-10 flex min-h-[68vh] max-w-2xl flex-col justify-end px-5 pb-14 pt-24 sm:px-8 lg:px-12"><span className="mb-3 text-[10px] font-semibold uppercase tracking-[.2em] text-emerald-400">{activeGroup}</span><h1 className="text-4xl font-semibold leading-none tracking-tight lg:text-6xl">{selected.name}</h1><p className="mt-4 text-sm text-white/45">{selected.episodes.length} episódios • {seasons.length} {seasons.length === 1 ? 'temporada' : 'temporadas'}</p><div className="mt-6 flex gap-3">{firstEpisode && <button onClick={() => onSelectChannel(firstEpisode.channel)} className="flex items-center gap-2 rounded-xl bg-emerald-400 px-5 py-3 text-sm font-semibold text-slate-950"><Play className="h-4 w-4 fill-current" />{progress[firstEpisode.channel.id] ? 'Continuar' : 'Reproduzir'}</button>}<button onClick={() => firstEpisode && onToggleFavorite(firstEpisode.channel.id)} className="flex items-center gap-2 rounded-xl bg-white/10 px-5 py-3 text-sm backdrop-blur"><Heart className={`h-4 w-4 ${firstEpisode && favorites.has(firstEpisode.channel.id) ? 'fill-emerald-400 text-emerald-400' : ''}`} />Favoritos</button></div></div></section>}
    <section className="px-5 pb-16 pt-6 sm:px-8 lg:px-12"><h2 className="mb-3 text-sm font-semibold text-white/75">Temporadas</h2><div className="mb-8 flex gap-2 overflow-x-auto scrollbar-none">{seasons.map((value) => <button key={value} onClick={() => setSeason(value)} className={`min-w-36 shrink-0 rounded-xl px-5 py-3 text-sm font-medium transition ${season === value ? 'bg-emerald-400 text-slate-950' : 'bg-white/[0.06] text-white/55 hover:bg-white/10'}`}>Temporada {value}</button>)}</div><h2 className="mb-4 text-lg font-semibold">Episódios</h2><div className="flex gap-4 overflow-x-auto pb-4 scrollbar-none">{episodes.map((item) => { const watched = progress[item.channel.id]; const percent = watched ? Math.min(100, Math.round((watched.current / watched.duration) * 100)) : 0; return <button key={item.channel.id} onClick={() => onSelectChannel(item.channel)} className="group w-[min(78vw,22rem)] shrink-0 text-left"><div className="relative aspect-video overflow-hidden rounded-2xl bg-white/[0.04]">{item.channel.logo ? <img src={item.channel.logo} alt="" className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /> : <span className="flex h-full items-center justify-center"><Tv className="h-8 w-8 text-white/15" /></span>}<div className="absolute inset-0 bg-gradient-to-t from-black/85 via-transparent to-transparent" />{percent > 0 && <span className="absolute inset-x-0 bottom-0 h-1.5 bg-white/15"><span className="block h-full bg-emerald-400" style={{ width: `${percent}%` }} /></span>}<span className="absolute bottom-4 left-4 text-sm font-semibold">Episódio {item.episode}</span></div><p className="mt-2 truncate text-xs text-white/45">{item.title}{percent > 0 ? ` • ${percent}% assistido` : ''}</p></button>; })}</div></section>
  </div>;
}
